# NewAl School: runs on Kaggle's free GPUs (T4 x2) while the user's laptop rests.
#
# NewAl sends the programming tasks it found hard on the user's computer (failed, or fixed only after several
# attempts). Here the same brain (Qwen3.6-35B-A3B, a larger quantization than the laptop's) works on each one:
# write -> run -> check -> fix, many more attempts than a laptop can afford. For every task it solves it writes
# the working program and one general lesson; NewAl downloads them into its lessons notebook and examples.
# The model's weights do not change (training this model needs ~74 GB of GPU memory); its notebook does.
#
# Generated by NewAl: the tasks and settings are embedded below.

import base64
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request

START = time.time()
CONFIG = json.loads(base64.b64decode("__CONFIG__").decode("utf-8"))
TASKS = json.loads(base64.b64decode("__TASKS__").decode("utf-8"))
OUT = os.environ.get("SCHOOL_OUT") or ("/kaggle/working" if os.path.isdir("/kaggle/working") else ".")
WORK = os.environ.get("SCHOOL_WORK") or "/tmp/newal-school"
DEADLINE = START + CONFIG["hours"] * 3600 - 20 * 60          # stop in time to save the results
PORT = 8080
os.makedirs(OUT, exist_ok=True)
os.makedirs(WORK, exist_ok=True)


def log(*args):
    print(time.strftime("%H:%M:%S"), *args, flush=True)


def sh(cmd, cwd=None, timeout=None):
    log("$", " ".join(cmd) if isinstance(cmd, list) else cmd)
    return subprocess.run(cmd, cwd=cwd, timeout=timeout, check=True, shell=isinstance(cmd, str))


# ------------------------------------------------------------------ the engine: llama.cpp with CUDA

def llama_server():
    if os.environ.get("LLAMA_SERVER"):
        return os.environ["LLAMA_SERVER"]
    # A build from an earlier session (this notebook's previous output) saves ~20 minutes.
    for old in glob.glob("/kaggle/input/*/llama-bin/llama-server") + glob.glob(os.path.join(OUT, "llama-bin", "llama-server")):
        dest = os.path.join(WORK, "llama-bin")
        shutil.copytree(os.path.dirname(old), dest, dirs_exist_ok=True)
        exe = os.path.join(dest, "llama-server")
        os.chmod(exe, 0o755)
        try:
            subprocess.run([exe, "--version"], capture_output=True, timeout=60, check=True)
            log("reusing llama.cpp build from", old)
            return exe
        except Exception as e:  # noqa: BLE001 - build again
            log("old build unusable:", e)
    src = os.path.join(WORK, "llama.cpp")
    if not os.path.isdir(src):
        sh(["git", "clone", "--depth", "1", "https://github.com/ggml-org/llama.cpp", src])
    cuda = bool(shutil.which("nvcc") or os.path.exists("/usr/local/cuda/bin/nvcc"))
    if cuda and not shutil.which("nvcc"):
        os.environ["PATH"] = "/usr/local/cuda/bin:" + os.environ["PATH"]
    if not shutil.which("cmake"):
        sh([sys.executable, "-m", "pip", "install", "-q", "cmake"])
    flags = ["-DLLAMA_CURL=OFF", "-DBUILD_SHARED_LIBS=OFF", "-DLLAMA_BUILD_TESTS=OFF", "-DCMAKE_BUILD_TYPE=Release"]
    if cuda:
        flags += ["-DGGML_CUDA=ON", "-DCMAKE_CUDA_ARCHITECTURES=" + CONFIG.get("cuda_arch", "75")]
    sh(["cmake", "-B", "build"] + flags, cwd=src)
    sh(["cmake", "--build", "build", "--target", "llama-server", "-j", str(os.cpu_count() or 4)], cwd=src)
    exe = os.path.join(src, "build", "bin", "llama-server")
    keep = os.path.join(OUT, "llama-bin")                   # for the next session
    os.makedirs(keep, exist_ok=True)
    shutil.copy2(exe, keep)
    return exe


def model_file():
    if os.environ.get("MODEL_PATH"):
        return os.environ["MODEL_PATH"]
    url = CONFIG["model_url"]
    free_gb = shutil.disk_usage(WORK).free / 1e9
    if free_gb < CONFIG.get("model_gb", 23) + 3 and CONFIG.get("model_url_small"):
        log("only %.0f GB free: using the smaller model" % free_gb)
        url = CONFIG["model_url_small"]
    path = os.path.join(WORK, os.path.basename(url))
    if not os.path.exists(path):
        log("downloading", url)
        req = urllib.request.Request(url, headers={"User-Agent": "NewAl-School"})
        with urllib.request.urlopen(req, timeout=60) as r, open(path + ".part", "wb") as f:
            shutil.copyfileobj(r, f, 1 << 24)
        os.replace(path + ".part", path)
    return path


def start_engine():
    exe, model = llama_server(), model_file()
    args = [exe, "-m", model, "--port", str(PORT), "-c", str(CONFIG.get("context", 32768)), "-np", "1", "--jinja",
            "-ngl", "999", "--no-webui"]
    log("starting engine")
    proc = subprocess.Popen(args, stdout=open(os.path.join(WORK, "engine.log"), "w"), stderr=subprocess.STDOUT)
    for _ in range(600):
        time.sleep(1)
        if proc.poll() is not None:
            print(open(os.path.join(WORK, "engine.log")).read()[-4000:])
            raise SystemExit("engine stopped")
        try:
            with urllib.request.urlopen("http://127.0.0.1:%d/health" % PORT, timeout=2) as r:
                if r.status == 200:
                    log("engine ready")
                    return proc
        except Exception:  # noqa: BLE001 - still loading
            pass
    raise SystemExit("engine did not start")


def chat(messages, max_tokens=4096, temperature=0.6, schema=None, think=True):
    body = {"messages": messages, "max_tokens": max_tokens, "temperature": temperature, "top_p": 0.95,
            "chat_template_kwargs": {"enable_thinking": think}}
    if schema:
        body["response_format"] = {"type": "json_schema", "json_schema": {"name": "answer", "schema": schema}}
    req = urllib.request.Request("http://127.0.0.1:%d/v1/chat/completions" % PORT, json.dumps(body).encode(),
                                 {"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=1800) as r:
        msg = json.loads(r.read())["choices"][0]["message"]
    text = msg.get("content") or ""
    return re.sub(r"<think>.*?</think>", "", text, flags=re.S).strip()


def ask_json(messages, schema, max_tokens=400):
    try:
        return json.loads(chat(messages, max_tokens=max_tokens, temperature=0, schema=schema, think=False))
    except Exception:  # noqa: BLE001
        return {}


# ------------------------------------------------------------------ programs (as NewAl reads them)

FENCE = re.compile(r"```([\w+-]*)[ \t]*([^\n`]*)\n(.*?)```", re.S)
PATH = re.compile(r"^(?:(?:path|file|title|filename)\s*[=:]\s*)?[\"']?([\w\-./]+\.[A-Za-z0-9]{1,6})[\"']?$")
RUN = re.compile(r"^\s*(?:\*\*)?RUN:?(?:\*\*)?:?\s*`?([^`\n]+?)`?\s*$", re.M | re.I)
RUNNERS = {"python": "python", "py": "python", "javascript": "node", "js": "node", "node": "node"}


def _defined(code):
    """Names a Python block defines at its top level: functions, classes, imports, assignments."""
    names = set(re.findall(r"^(?:async\s+)?(?:def|class)\s+(\w+)", code, re.M))
    names |= set(re.findall(r"^(\w+)\s*(?::[^=\n]+)?=(?!=)", code, re.M))
    for m in re.finditer(r"^(?:from\s+[\w.]+\s+)?import\s+(.+)$", code, re.M):
        for part in m.group(1).replace("(", "").replace(")", "").split(","):
            bits = part.split()
            if bits:
                names.add(bits[-1].split(".")[0])
    return names


def join_python(blocks):
    """The last Python block, plus the earlier ones when it uses what they define (function in one block,
    its tests in the next). A last block that stands on its own (a corrected full version) runs alone."""
    last = blocks[-1]
    earlier = set()
    for c in blocks[:-1]:
        earlier |= _defined(c)
    needed = {n for n in earlier - _defined(last) if re.search(r"\b%s\b" % re.escape(n), last)}
    if not needed:
        return last
    parts = []
    for c in blocks:
        if c not in parts:
            parts.append(c)
    return "\n\n".join(p.rstrip("\n") for p in parts) + "\n"


def program(answer, previous=None):
    files, run = {}, ""
    for lang, rest, code in FENCE.findall(answer):
        m = PATH.match(rest.strip())
        if m and ".." not in m.group(1) and not m.group(1).startswith("/"):
            files[m.group(1)] = code
    m = RUN.search(answer)
    run = m.group(1).strip() if m else ""
    if previous and previous["project"] and files:
        files = dict(previous["files"], **files)
        run = run or previous["run"]
    if len(files) >= 2:
        return {"project": True, "files": files, "run": run}
    # One program: Python blocks joined in order (function in one block, tests in the next), else the last block.
    blocks = [(RUNNERS.get(lang.lower()), code) for lang, rest, code in FENCE.findall(answer)]
    blocks = [(r, c) for r, c in blocks if r and c.strip()]
    if not blocks:
        return None
    if blocks[-1][0] != "python":
        return {"project": False, "files": {"main.js": blocks[-1][1]}, "run": ""}
    return {"project": False, "files": {"main.py": join_python([c for r, c in blocks if r == "python"])}, "run": ""}


def text_of(prog):
    return "\n\n".join("### %s\n%s" % (p, c) for p, c in prog["files"].items())


def run_program(prog, timeout=90):
    folder = tempfile.mkdtemp(dir=WORK, prefix="run-")
    for rel, code in prog["files"].items():
        path = os.path.join(folder, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
    names = list(prog["files"])
    if prog["run"] and re.match(r"^(python3?|py|pytest|node)\b", prog["run"]):
        cmd = re.sub(r"^(python3?|py)\b", sys.executable, prog["run"])
        cmd = re.sub(r"^pytest\b", sys.executable + " -m pytest", cmd)
    elif any(re.search(r"(^|/)(tests?/|test_)", n) for n in names):
        cmd = sys.executable + " -m pytest -q"
    else:
        main = next((n for n in names if n.split("/")[-1] in ("main.py", "app.py", "main.js", "index.js")), names[0])
        cmd = ("node " if main.endswith(".js") else sys.executable + " -X utf8 ") + main
    for _ in range(3):
        try:
            p = subprocess.run(cmd, shell=True, cwd=folder, capture_output=True, text=True, timeout=timeout,
                               stdin=subprocess.DEVNULL)
            out, code = (p.stdout + p.stderr)[-4000:], p.returncode
        except subprocess.TimeoutExpired:
            return False, "timed out after %d s" % timeout
        missing = re.search(r"No module named '?([\w]+)", out)
        if code != 0 and missing:
            name = {"cv2": "opencv-python", "PIL": "pillow", "sklearn": "scikit-learn", "yaml": "pyyaml",
                    "bs4": "beautifulsoup4", "docx": "python-docx"}.get(missing.group(1), missing.group(1))
            if subprocess.run([sys.executable, "-m", "pip", "install", "-q", name], capture_output=True).returncode == 0:
                continue
        if code == 5 and "pytest" in cmd and "-X utf8" not in cmd:
            # pytest found no test functions (asserts at the top of a file): run the program files instead.
            cmd = " && ".join("%s -X utf8 %s" % (sys.executable, n) for n in names if n.endswith(".py"))
            continue
        return code == 0, "$ %s\n%s\n(exit code %d)" % (cmd.replace(sys.executable, "python"), out, code)
    return False, out


def error_line(out):
    lines = [l.strip() for l in out.splitlines() if l.strip() and not l.startswith("(exit code")]
    for l in reversed(lines):
        if re.search(r"Error|Exception|error:|failed|Traceback|timed out", l):
            return l[:300]
    return lines[-1][:300] if lines else ""


VERDICT = {"type": "object", "properties": {"ok": {"type": "boolean"}, "reason": {"type": "string"}},
           "required": ["ok", "reason"]}
LESSON = {"type": "object", "properties": {"lesson": {"type": "string"}}, "required": ["lesson"]}


def verdict(task, code, output):
    return ask_json([{"role": "system", "content": CONFIG["judge_prompt"]},
                     {"role": "user", "content": "Request:\n%s\n\nCode:\n%s\n\nOutput:\n%s"
                                                 % (task[:2000], code[:6000], output[-2000:])}], VERDICT, 200)


def solve(task):
    """write -> run -> judge -> fix, with fresh starts when the fixes go in circles."""
    errors, tries = [], 0
    for start in range(CONFIG["restarts"]):
        messages = [{"role": "system", "content": CONFIG["coder_prompt"]},
                    {"role": "user", "content": task["request"] + (
                        "\n\nEarlier attempts failed with:\n" + "\n".join(errors[-6:]) +
                        "\nUse a different approach." if errors else "")}]
        answer = chat(messages, temperature=0.4 + 0.2 * start)
        prog, last = None, None
        for attempt in range(CONFIG["attempts"]):
            if time.time() > DEADLINE:
                return {"solved": False, "tries": tries, "errors": errors}
            prog = program(answer, prog)
            if not prog or prog == last:
                break
            last = prog
            code = text_of(prog)
            if re.search(r"\binput\s*\(|readline\(", code) and not any("test" in n for n in prog["files"]):
                errors.append("needs typed input")
                break
            tries += 1
            ok, out = run_program(prog)
            if ok:
                v = verdict(task["request"], code, out)
                if v.get("ok", True):
                    return {"solved": True, "tries": tries, "errors": errors, "answer": answer, "output": out,
                            "program": prog}
                problem = "The program ran but the result is wrong: %s\nOutput:\n%s" % (v.get("reason", ""), out[-1500:])
                errors.append("try %d: wrong result: %s" % (tries, (v.get("reason") or "?")[:250]))
            else:
                problem = "Running it failed:\n" + out[-2500:]
                errors.append("try %d: %s" % (tries, error_line(out) or out[-200:]))
            log("   try %d: %s" % (tries, errors[-1][:160]))
            messages = messages + [{"role": "assistant", "content": answer},
                                   {"role": "user", "content": "Fix the code. %s\nEarlier failed attempts:\n%s\n"
                                                               "Return the full corrected program." % (problem, "\n".join(errors[-5:]))}]
            answer = chat(messages, temperature=0.3)
    return {"solved": False, "tries": tries, "errors": errors}


def lesson(task, result):
    first = result["errors"][0] if result["errors"] else ""
    r = ask_json([{"role": "system", "content": CONFIG["lesson_prompt"]},
                  {"role": "user", "content": "Task: %s\n\nErrors in order:\n%s\n\nCode that finally worked:\n%s"
                                              % (task["request"][:600], "\n".join(result["errors"][:8]) or "(none: it "
                                                 "worked at once here; the user's first try had: %s)" % task.get("error", ""),
                                                 text_of(result["program"])[:4000])}], LESSON, 150)
    return (r.get("lesson") or "").strip()


def main():
    log("NewAl School: %d tasks, %.1f h" % (len(TASKS), CONFIG["hours"]))
    engine = start_engine()
    results = os.path.join(OUT, "results.jsonl")
    solved = done = 0
    try:
        for task in TASKS:
            if time.time() > DEADLINE:
                log("time is up")
                break
            t0 = time.time()
            log("task", task["id"], task["request"][:80].replace("\n", " "))
            try:
                r = solve(task)
            except Exception as e:  # noqa: BLE001 - one broken task must not end the session
                r = {"solved": False, "tries": 0, "errors": ["school error: %s" % e]}
            rec = {"id": task["id"], "request": task["request"], "solved": r["solved"], "tries": r["tries"],
                   "errors": r["errors"][-6:], "seconds": round(time.time() - t0)}
            if r["solved"]:
                rec.update(answer=r["answer"], output=r["output"][-1500:], lesson=lesson(task, r))
                solved += 1
            done += 1
            with open(results, "a", encoding="utf-8") as f:
                f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            log("  ->", "solved" if r["solved"] else "not solved", "after", r["tries"], "runs")
    finally:
        engine.terminate()
        with open(os.path.join(OUT, "summary.json"), "w") as f:
            json.dump({"tasks": len(TASKS), "done": done, "solved": solved,
                       "session_seconds": round(time.time() - START)}, f)
        shutil.rmtree(os.path.join(WORK, "llama.cpp"), ignore_errors=True)
        log("done: %d/%d solved" % (solved, done))


if __name__ == "__main__":
    main()
